site_name: mkdocs-mdpo-plugin
site_url: https://mondeja.github.io/mkdocs-mdpo-plugin/
site_description: Multilanguage HTTP request code snippet generator.
site_author: Álvaro Mondéjar Rubio

repo_url: https://github.com/mondeja/mkdocs-mdpo-plugin
repo_name: mkdocs-mdpo-plugin
edit_uri: tree/master/docs
copyright: Copyright &copy; 2021 Álvaro Mondéjar Rubio

extra_javascript:
  - assets/javascripts/language-selector.js
  - assets/javascripts/extensions-support.js
extra_css:
  - assets/stylesheets/pymdownx.progressbar.css

docs_dir: docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en

nav:
  - Home: index.md
  - Configuration: config.md
  - Extensions support:
      - Official extensions: extensions-support/oficial.md
      - PyMdown extensions: extensions-support/pymdownx.md
  - Tested plugins:
      - Navigation and page building: tested-plugins/navigation-and-page-building.md

markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - admonition
  - attr_list
  - def_list
  - fenced_code
  - footnotes
  - tables
  - legacy_attrs
  - wikilinks
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - include-markdown
  - exclude:
      glob:
        - file-to-be-inserted.txt
  - mdpo
  - minify:
      minify_html: true

extra:
  alternate:
    - name: English
      lang: en
    - name: Español
      link: es
      lang: es
