site_name: mkdocs-mdpo-plugin
site_url: https://mondeja.github.io/mkdocs-mdpo-plugin/
site_description: Multilanguage HTTP request code snippet generator.
site_author: Álvaro Mondéjar Rubio

repo_url: https://github.com/mondeja/mkdocs-mdpo-plugin
repo_name: mkdocs-mdpo-plugin
edit_uri: tree/master/docs
copyright: Copyright &copy; 2021 Álvaro Mondéjar Rubio

docs_dir: docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en

nav:
  - Home: index.md
  - Configuration: config.md
  - Extensions support: extensions-support.md

markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - admonition
  - attr_list
  - def_list
  - fenced_code
  - footnotes
  - tables
  - legacy_attrs
  - wikilinks
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed

plugins:
  - search
  - include-markdown
  - mdpo

extra:
  alternate:
    - name: English
      lang: en
    - name: Español
      link: es
      lang: es
