name: Documentation

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Documentation build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python v3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install .[doc]
          pip list
      - name: Show documentation configuration
        run: cat docs/conf.py
      - name: Test documentation build
        run: |
          python -m mkdocs build --strict
      - name: Show tree
        run: tree site
